export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_BASKET_SUCCESS = 'LOAD_BASKET_SUCCESS';
export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS';
export const UPDATE_BASKET_ZONE_SUCCESS = 'UPDATE_BASKET_ZONE_SUCCESS';
export const REMOVE_ITEM_FROM_BASKET_SUCCESS = 'REMOVE_ITEM_FROM_BASKET_SUCCESS';
export const RESET_BASKET_SUCCESS = 'RESET_BASKET_SUCCESS';
export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD';
