export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_BASKET_SUCCESS = 'LOAD_BASKET_SUCCESS';
export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS';
export const RESET_BASKET_SUCCESS = 'RESET_BASKET_SUCCESS';
