// API Actions
export const BEGIN_API_CALL = 'BEGIN_API_CALL';

// Product Actions
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';

// Basket Actions
export const LOAD_BASKET_SUCCESS = 'LOAD_BASKET_SUCCESS';
export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS';
export const UPDATE_BASKET_ZONE_SUCCESS = 'UPDATE_BASKET_ZONE_SUCCESS';
export const REMOVE_ITEM_FROM_BASKET_SUCCESS = 'REMOVE_ITEM_FROM_BASKET_SUCCESS';
export const RESET_BASKET_SUCCESS = 'RESET_BASKET_SUCCESS';

// User Actions
export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';

// Form Actions
export const UPDATE_VALIDITY = 'UPDATE_VALIDITY';
export const UPDATE_VALIDITY_ALL = 'UPDATE_VALIDITY_ALL';
